const express=require('express'),http=require('node:http'),{Server}=require('socket.io'),{randomBytes}=require('node:crypto');
const {QUESTIONS,KEYS,GROUP_KEY_IDS,KEY_OPTION_IDS,TASK_LABELS,GROUP_LABELS,EXIT_LABELS}=require('./public/content'),{SENTENCES,EVIDENCE_UNITS,PROFILES,DEMO_SOURCE,MODEL_OPTIONS}=require('./public/article'),{KEY_ANSWERS,WHO_ANSWERS,EVIDENCE,EVIDENCE_RULES,EXPLANATIONS,bridgeCorrect}=require('./curriculum');
const BRIDGE_REFERENCES=require('./bridge-reference');
const {createGuestPractice}=require('./guest-practice');
const {findByName}=require('./participant-resume');
const LESSON=require('./public/lesson-content'),LESSON_RULES=require('./lesson-rules');
const STAGES=['gist','demo','keys','bridgeDemo','combined','peer','summary','exit','awards'],CAPS=[2,2,2,2,3],GROUP_QUESTIONS=[[0],[1],[2],[3],[4,5]];
const MODEL={question:DEMO_SOURCE.question,key:DEMO_SOURCE.key,who:DEMO_SOURCE.who,evidence:DEMO_SOURCE.evidence};
const MODEL_KEYS=MODEL_OPTIONS;
const pct=(n,d)=>d?Math.round(100*n/d):0;
function editMarks(text,ranges,start,end,selected){if(!Number.isInteger(start)||!Number.isInteger(end)||start<0||end>text.length||start>=end||typeof selected!=='boolean')throw Error('Select valid text in the question.');const mask=Array(text.length).fill(false);ranges.forEach(r=>{for(let i=r.start;i<r.end;i++)mask[i]=true;});for(let i=start;i<end;i++)mask[i]=selected;const out=[];for(let i=0;i<mask.length;){if(!mask[i]){i++;continue;}let j=i+1;while(j<mask.length&&mask[j])j++;out.push({start:i,end:j});i=j;}return out;}
function hasMarks(text,ranges){return ranges.some(r=>text.slice(r.start,r.end).trim());}
const blankKeys=()=>Array(6).fill(null);
const blankMarks=()=>Array.from({length:6},()=>[]);
const blank=()=>({who:null,evidence:[]});
const bridgeDrafts=qs=>qs.map(()=>blank());
const freshGroups=()=>CAPS.map((capacity,i)=>{const qs=GROUP_QUESTIONS[i];return {id:i+1,q:qs[0],qs,capacity,markings:blankMarks(),drafts:{keys:blankKeys(),combined:bridgeDrafts(qs),peer:[]},submissions:{},feedback:null,target:null};});
function valid(a){return a&&['A','B','C','D'].includes(a.who)&&Array.isArray(a.evidence)&&a.evidence.length>=1&&a.evidence.length<=20&&new Set(a.evidence).size===a.evidence.length&&a.evidence.every(id=>[...SENTENCES,...EVIDENCE_UNITS].some(s=>s.id===id));}
function grade(q,a){return !!a&&a.who===WHO_ANSWERS[q]&&Array.isArray(a.evidence)&&bridgeCorrect(q,a.evidence);}
const demoPhaseCount=()=>DEMO_SOURCE.rows.length;
function groupQuestions(g){return g.qs||[g.q];}
function bridgeAnswers(g,source='initial'){const value=source==='draft'?g.drafts.combined:source==='submitted'?g.submissions.combined:g.submissions.combined||g.closedDrafts?.combined||g.drafts.combined;return Array.isArray(value)?value:[value||blank()];}
function answerFor(g,q,source='initial'){const i=groupQuestions(g).indexOf(q);return i<0?blank():(bridgeAnswers(g,source)[i]||blank());}
function initialAnswer(g){return answerFor(g,g.q);}
function groupHasBridge(g){return bridgeAnswers(g).some(hasBridge);}
function groupBridgeComplete(g,source='initial'){const answers=bridgeAnswers(g,source);return answers.length===groupQuestions(g).length&&answers.every(valid);}
function hasBridge(a){return !!a&&(!!a.who||a.evidence?.length>0);}
function closeDrafts(r,stage){r.groups.forEach(g=>{g.closedDrafts??={};if(g.submissions[stage]===undefined&&g.drafts[stage]!==undefined)g.closedDrafts[stage]=structuredClone(g.drafts[stage]);});}
function createApp({started=false}={}){const app=express(),server=http.createServer(app),io=new Server(server,{maxHttpBufferSize:16000}),rooms=new Map();app.use(express.static(__dirname+'/public'));app.get('/',(_,res)=>res.redirect('/teacher.html'));app.get('/health',(_,res)=>res.json({ok:true,version:'volunteers-reading-v3-five-groups'}));
function lessonGrade(stage,answer){if(stage==='exit')return answer.map((a,i)=>(grade(LESSON.exit.questions[i].q,a)&&a.key===KEY_ANSWERS[LESSON.exit.questions[i].q]));const rules=LESSON_RULES[stage];return rules?answer.map((v,i)=>v===rules[i]):null;}
function lessonPublic(r,s){const stage=STAGES[r.step],d=LESSON[stage];s.lesson=true;s.expected=r.groups.length;s.revealed=stage==='summary'||!!r.revealed[stage];s.submitted=r.groups.filter(g=>g.lessonAnswers?.[stage]!==undefined).length;s.groups.forEach((g,i)=>{g.submitted=r.groups[i].lessonAnswers?.[stage]!==undefined;g.completionOrder=r.groups[i].lessonOrder?.[stage]??null;});delete s.accuracy;if(s.revealed){s.lessonRows=r.groups.map(g=>{const answer=g.lessonAnswers?.[stage];return {group:g.id,answer:answer??null,correct:answer===undefined?null:lessonGrade(stage,answer)};});if(LESSON_RULES[stage]&&stage!=='response')s.lessonSolutions=LESSON_RULES[stage];if(stage==='response')s.responseModel=LESSON_RULES.responseModel;if(stage==='exit')s.exitReferences=[6,7].map(q=>({q,who:WHO_ANSWERS[q],evidence:EVIDENCE[q],explanation:EXPLANATIONS[q],reference:BRIDGE_REFERENCES[q],rule:EVIDENCE_RULES[q],key:KEY_ANSWERS[q]}));}return s;}

function scoreboard(r){const phases=[{id:'gist',points:10,correct:g=>g.lessonAnswers?.gist?lessonGrade('gist',g.lessonAnswers.gist).filter(Boolean).length:0,full:LESSON.gist.questions.length,open:!!r.revealed.gist},{id:'keys',points:10,correct:g=>g.submissions.keys?.filter((k,q)=>k===KEY_ANSWERS[q]).length||0,full:6,open:!!r.revealed.keys},{id:'combined',points:30,correct:g=>g.submissions.combined&&groupQuestions(g).every(q=>grade(q,answerFor(g,q,'submitted')))?1:0,full:1,open:!!(r.revealed.peer||r.revealed.combined)},{id:'peer',points:5,correct:g=>{const target=r.groups[g.target-1];if(!g.feedback||!target||!groupHasBridge(target))return 0;const allCorrect=groupQuestions(target).every(q=>grade(q,answerFor(target,q)));return (g.feedback.status==='approved')===allCorrect?1:0;},full:1,open:!!r.revealed.peer},{id:'exit',points:20,correct:g=>g.lessonAnswers?.exit?lessonGrade('exit',g.lessonAnswers.exit).filter(Boolean).length:0,full:2,open:!!r.revealed.exit}];const scores=r.groups.map(g=>({group:g.id,accuracy:0,speed:0,total:0,phases:{}}));for(const phase of phases.filter(p=>p.open)){for(const row of scores){const g=r.groups[row.group-1];const base=phase.correct(g)*phase.points;let bonus=0;row.accuracy+=base;if(phase.correct(g)===phase.full&&g.submitTime?.[phase.id]&&r.phaseStarted?.[phase.id]){const elapsed=Math.max(0,g.submitTime[phase.id]-r.phaseStarted[phase.id]);bonus=elapsed<=150000?3:elapsed<=240000?2:1;row.speed+=bonus;}row.phases[phase.id]=base+bonus;row.total=row.accuracy+row.speed;}}return scores.sort((a,b)=>b.total-a.total||b.accuracy-a.accuracy||a.group-b.group);}

function cohort(r){return r.groups.filter(g=>g.submissions.combined||bridgeAnswers(g).some(hasBridge));}
function publicState(r){const stage=STAGES[r.step],gs=r.groups,students=[...r.students.values()],initial=cohort(r),submitted=stage==='exit'?students.filter(s=>s.exit):gs.filter(g=>g.submissions[stage]!==undefined);const s={classStarted:!!r.started,warmup:r.warmup||{started:false,stage:0},version:'volunteers-reading-v3-five-groups',code:r.code,roomId:r.id,round:r.round,stage,step:r.step,finalOrder:r.finalOrder||null,exitMode:r.finalOrder==='awards-first'?'homework':'class',revealed:r.revealed[stage]||false,expected:stage==='exit'?Math.max(r.expectedStudents,r.students.size):gs.length,expectedStudents:r.expectedStudents,observers:[...r.observers.values()].filter(o=>o.sockets.size).length,submitted:submitted.length,joined:students.length,connected:students.filter(s=>s.sockets.size).length,reviewed:gs.filter(g=>g.feedback).length,draftCount:initial.length,groups:gs.map(g=>({id:g.id,q:g.q,qs:groupQuestions(g),capacity:g.capacity,members:students.filter(s=>s.group===g.id).map(s=>({name:s.name,connected:!!s.sockets.size,exitSubmitted:!!s.exit})),submitted:g.submissions[stage]!==undefined,reviewed:!!g.feedback,hasDraft:groupHasBridge(g),originalTimedOut:g.submissions.combined===undefined&&g.closedDrafts?.combined!==undefined,revisionTimedOut:g.submissions.peer===undefined&&g.closedDrafts?.peer!==undefined,keyCompleted:g.drafts.keys.filter(Number.isInteger).length,keyMarked:g.markings.filter((ranges,q)=>hasMarks(QUESTIONS[q],ranges)).length})),demo:['demo','bridgeDemo'].includes(stage)?r.demo:undefined};
if(stage==='peer'){s.submitted=gs.filter(g=>g.feedback).length;s.groups.forEach((g,i)=>{g.submitted=!!gs[i].feedback;g.checkTarget=gs[i].target;g.checkStatus=gs[i].feedback?.status||null;});}s.awardsChoices=gs.map(g=>({group:g.id,award:g.award??null}));s.awardsCelebrating=!!r.awardsCelebrating;s.answersShown=!!r.answersShown?.[stage];s.scoreRound={keys:r.keysAttempt||0,bridge:r.bridgeAttempt||0};if(r.revealed.gist||r.revealed.keys||r.revealed.peer||r.revealed.exit)s.scoreboard=scoreboard(r);if(LESSON[stage])return lessonPublic(r,s);
if(s.revealed&&!['demo','bridgeDemo'].includes(stage)){
 const questions=stage==='exit'?[6,7]:[0,1,2,3,4,5];
 s.scoredCount=stage==='exit'?submitted.length:stage==='peer'?initial.length:submitted.length;
 s.accuracy=questions.map(q=>{
  let answers=[],before=[],owner=null;
  if(stage==='exit')answers=submitted.map(p=>p.exit[q-6]);
  else if(stage==='keys')answers=gs.filter(g=>g.submissions.keys!==undefined).map(g=>g.submissions.keys[q]);
  else {
   owner=gs.find(g=>groupQuestions(g).includes(q));
   if(owner){const answer=answerFor(owner,q);if(hasBridge(answer)||owner.submissions.combined)answers=[answer];if(hasBridge(answer))before=[answer];}
  }
  const correct=answers.filter(a=>stage==='keys'?a===KEY_ANSWERS[q]:grade(q,a)&&(stage!=='exit'||a.key===KEY_ANSWERS[q])).length;
  return {q,correct,total:answers.length,percent:pct(correct,answers.length),beforePercent:pct(before.filter(a=>owner?.submissions.combined&&grade(q,a)).length,before.length),markings:stage==='keys'||stage==='exit'?[]:owner?.markings[q]||[],reviewEvidenceCorrect:stage==='keys'||stage==='exit'?undefined:bridgeCorrect(q,answerFor(owner,q).evidence),reviewWhoCorrect:stage==='keys'||stage==='exit'?undefined:answerFor(owner,q).who===WHO_ANSWERS[q],reviewAnswer:stage==='peer'&&owner?answerFor(owner,q):undefined,originalSubmitted:stage==='peer'?owner?.submissions.combined!==undefined:undefined,groupMarkings:stage==='keys'?gs.map(g=>({group:g.id,ranges:g.markings[q]})):undefined,groupKeys:stage==='keys'?gs.map(g=>({group:g.id,key:g.submissions.keys?.[q]??g.drafts.keys[q]??null,submitted:g.submissions.keys!==undefined})):undefined,reference:stage==='keys'?{parts:BRIDGE_REFERENCES[q].parts,keyParts:BRIDGE_REFERENCES[q].keyParts}:BRIDGE_REFERENCES[q],choices:stage==='keys'?[]:[...new Set(answers.flatMap(a=>a.evidence))],key:KEY_ANSWERS[q],answer:stage==='keys'?undefined:WHO_ANSWERS[q],evidence:stage==='keys'?undefined:EVIDENCE[q],rule:stage==='keys'?undefined:EVIDENCE_RULES[q],explanation:stage==='keys'?undefined:EXPLANATIONS[q],evidencePercent:stage==='keys'?undefined:pct(answers.filter(a=>bridgeCorrect(q,a.evidence)).length,answers.length),whoPercent:stage==='keys'?undefined:pct(answers.filter(a=>a.who===WHO_ANSWERS[q]).length,answers.length)};
 });
 s.overallAccuracy=pct(s.accuracy.reduce((n,a)=>n+a.correct,0),s.accuracy.reduce((n,a)=>n+a.total,0));
 if(stage==='peer'){const taskRows=gs.flatMap(g=>groupQuestions(g).map(q=>({g,q,a:answerFor(g,q)}))).filter(x=>hasBridge(x.a));s.beforeAccuracy=pct(taskRows.filter(x=>x.g.submissions.combined&&grade(x.q,x.a)).length,taskRows.length);s.revisedCount=gs.filter(g=>g.feedback).length;}
}
return s;}
const guestRoom=createGuestPractice({STAGES,CAPS,GROUP_QUESTIONS,blankKeys,blankMarks,blank,bridgeDrafts,closeDrafts,initialAnswer});
function practiceResult(r,s){if(!r.guestPractice)return null;const stage=STAGES[r.step],g=r.groups[s.group-1];if(!r.revealed[stage])return null;if(LESSON[stage]){const a=g.lessonAnswers?.[stage]??g.lessonDrafts?.[stage];return a?{submitted:g.lessonAnswers?.[stage]!==undefined,correct:lessonGrade(stage,a)}:null;}const a=g.submissions[stage]??g.drafts[stage];return a?{submitted:g.submissions[stage]!==undefined,correct:stage==='keys'?a.map((k,q)=>k===KEY_ANSWERS[q]):['combined','peer'].includes(stage)?groupQuestions(g).map(q=>grade(q,answerFor(g,q,g.submissions.combined?'submitted':'draft'))):null}:null;}
function privateState(r,s){if(!(r.guestPractice?r.source.started:r.started))return {observer:!!s.observer,practice:!!s.practice,stage:STAGES[r.step],round:r.round,group:s.group,notes:'',notesRevision:0,lessonAnswer:null,lessonDraft:null};if(s.practice&&!r.guestPractice)r=guestRoom(r,s);const stage=STAGES[r.step],g=r.groups[s.group-1],target=(r.guestPractice?r.source.groups:r.groups).find(p=>p.id===g.target),reviewer=r.groups.find(p=>p.target===g.id&&p.feedback),qs=groupQuestions(g);return {observer:!!s.observer,practice:!!s.practice,practiceResult:practiceResult(r,s),stage,round:r.round,group:g.id,q:g.q,qs,capacity:g.capacity,keyMarkings:g.markings,markings:g.markings[g.q],keyIdea:r.step>=STAGES.indexOf('combined')?KEY_ANSWERS[g.q]:undefined,keyIdeas:r.step>=STAGES.indexOf('combined')?qs.map(q=>KEY_ANSWERS[q]):undefined,draft:stage==='keys'?g.drafts.keys:stage==='peer'?g.drafts.peer:g.drafts.combined,answers:g.submissions[stage]??null,eligible:!!g.target,original:stage==='peer'?bridgeAnswers(g):g.submissions.combined||null,initialSubmitted:g.submissions.combined!==undefined,originalTimedOut:g.submissions.combined===undefined&&g.closedDrafts?.combined!==undefined,target:stage==='peer'&&target?{group:target.id,qs:groupQuestions(target),tasks:groupQuestions(target).map(q=>({q,markings:structuredClone(target.markings[q]),answer:answerFor(target,q),keyIdea:KEY_ANSWERS[q]})),submitted:target.submissions.combined!==undefined,timedOut:target.submissions.combined===undefined}:null,sent:stage==='peer'?g.feedback:null,received:stage==='peer'&&reviewer?{group:reviewer.id,...reviewer.feedback}:null,lessonDraft:g.lessonDrafts?.[stage]??null,lessonAnswer:g.lessonAnswers?.[stage]??null,notes:s.notes||'',notesRevision:s.notesRevision||0,exitAnswers:s.exit||null};}
function roomAvailability(r){const students=[...r.students.values()];return r.groups.map(g=>{const member=students.find(s=>s.group===g.id);return {id:g.id,inUse:!!member,connected:!!member?.sockets.size};});}
function broadcast(r){if(r.guestPractice){for(const id of r.owner.sockets)io.to(id).emit('group:personal',privateState(r,r.owner));return;}io.to(r.code).emit('room:state',publicState(r));for(const s of [...r.students.values(),...r.observers.values()])for(const id of s.sockets)io.to(id).emit('group:personal',privateState(r,s));}
function attach(socket,r,role,id){if(socket.data.code&&(socket.data.code!==r.code||socket.data.role!==role||socket.data.id!==id))throw Error('This tab is already in another session. Open a new tab to switch.');socket.join(r.code);Object.assign(socket.data,{code:r.code,role,id});}
io.on('connection',socket=>{const handle=(e,fn)=>socket.on(e,(p,ack)=>{try{const res=fn(p||{});if(typeof ack==='function')ack({ok:true,...res});}catch(e){if(typeof ack==='function')ack({ok:false,error:e.message});}});
function teacher(p){const r=rooms.get(p.code);if(!r||r.token!==p.token)throw Error('Use your original teacher tab.');return r;}
function current(r,p){if(!(r.guestPractice?r.source.started:r.started))throw Error('Wait for your teacher to START CLASS.');if(p.round!==r.round||p.stage!==STAGES[r.step])throw Error('The activity changed. Use the current step.');}
function student(){let r=rooms.get(socket.data.code);const o=r?.observers.get(socket.data.id);if(socket.data.role==='observer'&&o?.practice){r=guestRoom(r,o);return {r,s:o,g:r.groups[o.group-1]};}const s=r?.students.get(socket.data.id);if(socket.data.role!=='student'||!s)throw Error('Join the room first.');return {r,s,g:r.groups[s.group-1]};}
handle('teacher:start',p=>{if(socket.data.role!=='teacher'||socket.data.code!==p.code)throw Error('Only the teacher can START CLASS.');const r=teacher(p);r.started=true;r.warmup={started:true,stage:4};r.phaseStarted??={};r.phaseStarted.gist??=Date.now();broadcast(r);return {state:publicState(r)};});
handle('teacher:warmup',p=>{if(socket.data.role!=='teacher'||socket.data.code!==p.code)throw Error('Only the teacher can control the warm-up.');const r=teacher(p);if(r.started)throw Error('The reading activity has already started.');if(typeof p.started!=='boolean'||!Number.isInteger(p.warmupStage)||p.warmupStage<0||p.warmupStage>4)throw Error('Choose a valid warm-up step.');r.warmup={started:p.started,stage:p.warmupStage};broadcast(r);return {state:publicState(r)};});
handle('teacher:newClass',p=>{const old=teacher(p);for(const active of io.sockets.sockets.values())if(active.id!==socket.id&&active.data.code===old.code&&active.data.role!=='teacher'){active.emit('room:closed',{code:old.code});active.disconnect(true);}const r={code:old.code,started:false,warmup:{started:false,stage:0},expectedStudents:old.expectedStudents,observers:new Map(),id:randomBytes(12).toString('hex'),token:old.token,step:0,round:1,revealed:{},demo:{key:null,who:null,evidence:[],revealed:false,phase:0,markings:[]},students:new Map(),groups:freshGroups(),lastActive:Date.now()};rooms.set(r.code,r);broadcast(r);return {state:publicState(r)};});
handle('teacher:join',p=>{const code=String(p.code||'').trim().toUpperCase();if(!/^[A-Z0-9]{3,12}$/.test(code))throw Error('Use a room code of 3–12 letters or numbers.');let r=rooms.get(code),created=!r;if(!r&&p.resumeOnly)throw Error('房间已失效，请返回老师页面重新建房间。');if(r&&r.token!==p.token){if(p.takeover!==true)throw Error('This room was reopened elsewhere. Use the latest teacher tab.');const emptyFixedRoom=code==='VOL5G'&&r.students.size===0;if(emptyFixedRoom){for(const active of io.sockets.sockets.values())if(active.id!==socket.id&&active.data.role==='teacher'&&active.data.code===code)active.disconnect(true);rooms.delete(code);r=null;created=true;}else{const teacherOnline=[...io.sockets.sockets.values()].some(active=>active.id!==socket.id&&active.data.role==='teacher'&&active.data.code===code);if(code!=='VOL5G'||teacherOnline)throw Error('This room code is in use. Choose another.');r.token=randomBytes(24).toString('hex');}}if(!r){const expectedStudents=Number(p.expected??5);if(!Number.isInteger(expectedStudents)||expectedStudents<0||expectedStudents>Number.MAX_SAFE_INTEGER)throw Error('Enter a valid expected count, or leave it blank.');r={code,started,warmup:{started:false,stage:0},expectedStudents,observers:new Map(),id:randomBytes(12).toString('hex'),token:randomBytes(24).toString('hex'),step:0,round:1,revealed:{},demo:{key:null,who:null,evidence:[],revealed:false,phase:0,markings:[]},students:new Map(),groups:CAPS.map((capacity,i)=>{const qs=GROUP_QUESTIONS[i];return {id:i+1,q:qs[0],qs,capacity,markings:blankMarks(),drafts:{keys:blankKeys(),combined:bridgeDrafts(qs),peer:[]},submissions:{},feedback:null,target:null};}),lastActive:Date.now()};rooms.set(code,r);}attach(socket,r,'teacher');broadcast(r);return {created,token:r.token,state:publicState(r)};});
handle('room:availability',p=>{const code=String(p.code||'').trim().toUpperCase(),r=rooms.get(code);if(!r)throw Error('Room not found. Ask your teacher.');return {code,groups:roomAvailability(r)};});
handle('student:join',p=>{if(socket.data.role&&socket.data.role!=='student')throw Error('Open a separate tab to join as a student.');const r=rooms.get(String(p.code||'').trim().toUpperCase());if(!r)throw Error('Room not found. Ask your teacher.');if(typeof p.clientId!=='string'||! /^[\w-]{8,80}$/.test(p.clientId))throw Error('Reload to create a student session.');let s=r.students.get(p.clientId);if(!s){const remembered=findByName(r.students,p.name,p.group);if(remembered&&remembered.group!==Number(p.group))throw Error('This name belongs to Group '+remembered.group+'. Choose that group to restore it.');s=remembered;}const resumed=!!s;if(!s){const group=Number(p.group),g=r.groups[group-1],name=String(p.name||'').trim();if(!g||!Number.isInteger(group))throw Error('Choose Group 1–5.');if(!name||name.length>40)throw Error('Enter your name (1–30 characters).');if(r.students.size&&[...r.students.values()].some(member=>member.group===group))throw Error('Group '+group+' is already taken. Please choose another OPEN group.');if(r.revealed.exit)throw Error('The exit ticket has closed.');s={id:p.clientId,name,group,sockets:new Set(),exit:null};r.students.set(s.id,s);}attach(socket,r,'student',s.id);s.sockets.add(socket.id);r.lastActive=Date.now();broadcast(r);return {resumed,name:s.name,group:s.group,state:publicState(r),personal:privateState(r,s)};});
handle('observer:join',p=>{if(socket.data.role&&socket.data.role!=='observer')throw Error('Open a separate tab for the viewing mode.');const r=rooms.get(String(p.code||'').trim().toUpperCase());if(!r)throw Error('Room not found. Ask your teacher.');if(typeof p.clientId!=='string'||! /^[\w-]{8,80}$/.test(p.clientId))throw Error('Reload to create a viewing session.');const group=Number(p.group||1);if(!Number.isInteger(group)||!r.groups[group-1])throw Error('Choose Group 1–5.');const named=String(p.name||'').trim();let o=r.observers.get(p.clientId)||(p.practice===true&&named&&named.toLowerCase()!=='guest'?findByName(new Map([...r.observers].filter(([,o])=>o.practice)),named,p.group):null);const resumed=!!o;if(!o){o={id:p.clientId,name:String(p.name||'Guest').trim().slice(0,30)||'Guest',group,observer:true,practice:p.practice===true,sockets:new Set()};r.observers.set(o.id,o);}attach(socket,r,'observer',o.id);o.sockets.add(socket.id);r.lastActive=Date.now();broadcast(r);return {resumed,name:o.name,group:o.group,observer:true,practice:!!o.practice,state:publicState(r),personal:privateState(r,o)};});
handle('observer:group',p=>{const r=rooms.get(socket.data.code),o=r?.observers.get(socket.data.id);if(socket.data.role!=='observer'||!o)throw Error('Join viewing mode first.');const group=Number(p.group);if(!Number.isInteger(group)||!r.groups[group-1])throw Error('Choose Group 1–5.');o.group=group;return {personal:privateState(r,o)};});
function exportRecord(r,participant){if(participant&&(!['exit','homework','awards'].includes(STAGES[r.step])||!r.revealed.exit))throw Error('Reveal the exit ticket before exporting your learning record.');const gs=participant?[r.groups[participant.group-1]]:r.groups;return {scope:participant?'student':'class',code:r.code,round:r.round,createdAt:new Date().toISOString(),scoreboard:scoreboard(r),name:participant?.name,group:participant?.group,notes:participant?.notes||'',lessonDefinitions:LESSON,lessonSolutions:Object.fromEntries(Object.entries(LESSON_RULES).filter(([stage])=>r.revealed[stage]||stage==='responseModel'&&r.revealed.response)),exitReferences:r.revealed.exit?[6,7].map(q=>({q,who:WHO_ANSWERS[q],evidence:EVIDENCE[q],key:KEY_ANSWERS[q],explanation:EXPLANATIONS[q]})):[],students:participant?undefined:[...r.students.values()].map(s=>({name:s.name,group:s.group,notes:s.notes||''})),groups:gs.map(g=>{const reviewer=r.groups.find(x=>x.target===g.id);return {lessonAnswers:g.lessonAnswers||{},lessonDrafts:g.lessonDrafts||{},closedDrafts:g.closedDrafts||{},initialSubmitted:g.submissions.combined!==undefined,originalTimedOut:g.submissions.combined===undefined&&g.closedDrafts?.combined!==undefined,revisedSubmitted:g.submissions.peer!==undefined,revisionTimedOut:g.submissions.peer===undefined&&g.closedDrafts?.peer!==undefined,exitGrade:r.revealed.exit&&g.lessonAnswers?.exit?lessonGrade('exit',g.lessonAnswers.exit):null,id:g.id,q:g.q,qs:groupQuestions(g),members:[...r.students.values()].filter(s=>s.group===g.id).map(s=>s.name),markings:structuredClone(g.markings),keys:g.submissions.keys||g.closedDrafts?.keys||null,keysSubmitted:g.submissions.keys!==undefined,initial:bridgeAnswers(g).map((a,i)=>hasBridge(a)?{q:groupQuestions(g)[i],...a}:null),initialCorrect:(r.revealed.combined||r.revealed.peer)&&g.submissions.combined!==undefined?groupQuestions(g).map(q=>grade(q,answerFor(g,q,'submitted'))):null,revisedCorrect:r.revealed.peer&&g.submissions.peer!==undefined?grade(g.q,g.submissions.peer):null,revised:g.submissions.peer||g.closedDrafts?.peer||null,target:g.target,sent:g.feedback?{group:g.target,...g.feedback}:null,received:reviewer?.feedback?{group:reviewer.id,...reviewer.feedback}:null};}),groupKeyIds:GROUP_KEY_IDS,taskLabels:TASK_LABELS,exitLabels:EXIT_LABELS,questions:QUESTIONS,keys:KEYS,keyNumbers:KEYS.map((k,i)=>KEY_OPTION_IDS.indexOf(i)+1),sentences:[...SENTENCES,...EVIDENCE_UNITS],profiles:PROFILES,references:KEY_ANSWERS.slice(0,6).map((key,q)=>({q,...(r.revealed.keys?{key}:{}),...((r.revealed.combined||r.revealed.peer)?{who:WHO_ANSWERS[q],evidence:EVIDENCE[q],explanation:EXPLANATIONS[q]}:{})}))};}
handle('student:notes',p=>{const {r,s}=student();current(r,p);if(!['exit','homework','awards'].includes(STAGES[r.step])||typeof p.notes!=='string'||p.notes.length>4000)throw Error('Use at most 4000 characters in your final reflection.');s.notes=p.notes;s.notesRevision=(s.notesRevision||0)+1;return {personal:privateState(r,s)};});
handle('student:record',()=>{const {r,s}=student();return {record:{...exportRecord(r,s),practice:!!s.practice}};});
handle('teacher:record',p=>{if(socket.data.role!=='teacher'||socket.data.code!==p.code)throw Error('Only the teacher can export class records.');const r=teacher(p);return {record:exportRecord(r)};});
handle('teacher:demo',p=>{const r=teacher(p);current(r,p);if(!['demo','bridgeDemo'].includes(STAGES[r.step])||r.demo.revealed)throw Error('Demo is closed.');if(p.field==='mark'){if(STAGES[r.step]!=='demo')throw Error('Mark the question in the Key Idea demo.');const v=p.value||{};r.demo.markings=editMarks(MODEL.question,r.demo.markings||[],v.start,v.end,v.selected);}else if(p.field==='phase'){if(STAGES[r.step]!=='bridgeDemo'||!Number.isInteger(p.value)||p.value<0||p.value>demoPhaseCount())throw Error('Invalid demo step.');r.demo.phase=p.value;if(p.value===demoPhaseCount()){r.demo={...MODEL,markings:r.demo.markings||[],phase:demoPhaseCount(),revealed:true};r.revealed.bridgeDemo=true;}}else if(p.field==='key'){if(!MODEL_KEYS.includes(p.value))throw Error('Choose a demo key.');r.demo.key=p.value;if(STAGES[r.step]==='demo'&&p.value===MODEL.key){r.demo.revealed=true;r.revealed.demo=true;}}else if(p.field==='who'){if(!['A','B','C','D'].includes(p.value))throw Error('Choose A, B, C or D.');r.demo.who=p.value;}else if(p.field==='evidence'){if(![...SENTENCES,...EVIDENCE_UNITS].some(s=>s.id===p.value))throw Error('Unknown sentence.');const ids=r.demo.evidence,i=ids.indexOf(p.value);if(i>=0)ids.splice(i,1);else if(ids.length<20)ids.push(p.value);else throw Error('Select at most 20 text fragments.');}else throw Error('Unknown demo action.');broadcast(r);return {};});
handle('group:mark',p=>{const {r,s,g}=student();current(r,p);if(STAGES[r.step]!=='keys'||r.revealed.keys||g.submissions.keys!==undefined)throw Error('This group question is closed.');if(!Number.isInteger(p.q)||p.q<0||p.q>5)throw Error('Choose question a–f.');g.markings[p.q]=editMarks(QUESTIONS[p.q],g.markings[p.q],p.start,p.end,p.selected);broadcast(r);return {personal:privateState(r,s)};});
handle('group:draft',p=>{const {r,s,g}=student();current(r,p);const stage=STAGES[r.step];if(!['keys','combined'].includes(stage)||r.revealed[stage]||g.submissions[stage]!==undefined)throw Error('This group answer is closed.');if(stage==='keys'){if(p.field!=='key'||!Number.isInteger(p.q)||p.q<0||p.q>5||!KEY_OPTION_IDS.includes(p.value))throw Error('Choose one of the nine Key Ideas.');g.drafts.keys[p.q]=p.value;}else{const q=Number(p.q),index=groupQuestions(g).indexOf(q);if(index<0)throw Error('Choose one of your assigned questions.');const d=g.drafts.combined[index];if(p.field==='who'){if(!['A','B','C','D'].includes(p.value))throw Error('Choose A, B, C or D.');d.who=p.value;}else if(p.field==='evidence'){if(![...SENTENCES,...EVIDENCE_UNITS].some(s=>s.id===p.value))throw Error('Unknown sentence.');const i=d.evidence.indexOf(p.value);if(p.selected===false){if(i>=0)d.evidence.splice(i,1);}else if(i<0){if(d.evidence.length>=20)throw Error('Choose at most 20 text fragments.');d.evidence.push(p.value);}}else throw Error('Unknown field.');}broadcast(r);return {personal:privateState(r,s)};});
handle('group:submit',p=>{const {r,s,g}=student();current(r,p);const stage=STAGES[r.step];if(!['keys','combined'].includes(stage)||r.revealed[stage]||g.submissions[stage]!==undefined)throw Error('Your group already submitted or this step is closed.');if(stage==='keys'){const missing=g.markings.map((ranges,q)=>hasMarks(QUESTIONS[q],ranges)?null:GROUP_LABELS[q]).filter(Boolean);if(missing.length)throw Error('Underline key words in questions '+missing.join(', ')+', then submit all six group answers.');}const d=g.drafts[stage];if(stage==='keys'?(d.length!==6||d.some(k=>!Number.isInteger(k))):(d.length!==groupQuestions(g).length||d.some(a=>!valid(a))))throw Error('Complete every assigned group answer first.');g.submissions[stage]=structuredClone(d);g.submitTime??={};g.submitTime[stage]=Date.now();broadcast(r);return {personal:privateState(r,s)};});
handle('group:feedback',p=>{const {r,s,g}=student();current(r,p);if(STAGES[r.step]!=='peer'||r.revealed.peer||!g.target||g.feedback)throw Error('Peer check is closed or already sent.');if(!['approved','revise'].includes(p.status)||typeof p.note!=='string'||p.note.length>160)throw Error('Choose APPROVED / REVISE; reason at most 160 characters.');g.feedback={status:p.status,note:p.note.trim()};broadcast(r);return {personal:privateState(r,s)};});
handle('legacy-exit:submit',p=>{const {r,s}=student();current(r,p);if(STAGES[r.step]!=='exit'||r.revealed.exit||s.exit)throw Error('Exit ticket closed or already submitted.');if(!Array.isArray(p.answers)||p.answers.length!==2||p.answers.some((a,i)=>!valid(a)||a.key!==undefined&&(!Number.isInteger(a.key)||a.key<0||a.key>7)))throw Error('Complete both exit questions with evidence and Who.');if(p.answers.some(a=>!Number.isInteger(a.key)||a.key<0||a.key>7))throw Error('Choose a Key Idea for both exit questions.');s.exit=structuredClone(p.answers);broadcast(r);return {personal:privateState(r,s)};});
handle('group:award',p=>{const {r,s,g}=student();current(r,p);if(STAGES[r.step]!=='awards'||r.awardsCelebrating||!Number.isInteger(p.award)||p.award<0||p.award>5)throw Error('Choose one of the six awards before the celebration.');g.award=p.award;broadcast(r);return {personal:privateState(r,s)};});
handle('teacher:celebrate',p=>{const r=teacher(p);current(r,p);if(STAGES[r.step]!=='awards')throw Error('Open Matching Superpowers first.');r.awardsCelebrating=true;broadcast(r);return {};});
handle('teacher:final-route',p=>{const r=teacher(p);current(r,p);if(STAGES[r.step]!=='summary')throw Error('Choose the final order after Recapture.');if(!['exit-first','awards-first'].includes(p.order))throw Error('Choose a valid final order.');r.finalOrder=p.order;r.step=STAGES.indexOf(p.order==='awards-first'?'awards':'exit');r.phaseStarted??={};if(p.order==='exit-first'&&!r.phaseStarted.exit)r.phaseStarted.exit=Date.now();broadcast(r);return {};});
handle('teacher:answers',p=>{const r=teacher(p);current(r,p);const stage=STAGES[r.step];if(!r.revealed[stage])throw Error('Show the scores first.');r.answersShown??={};r.answersShown[stage]=true;broadcast(r);return {};});
handle('teacher:reveal',p=>{const r=teacher(p);current(r,p);const stage=STAGES[r.step];if(LESSON[stage]){r.revealed[stage]=true;broadcast(r);return {};}if(stage==='demo'||stage==='bridgeDemo'){r.demo={...MODEL,markings:r.demo.markings||[],phase:stage==='bridgeDemo'?demoPhaseCount():0,revealed:true};r.revealed[stage]=true;}else{const count=stage==='exit'?[...r.students.values()].filter(s=>s.exit).length:stage==='peer'?cohort(r).length:r.groups.filter(g=>g.submissions[stage]!==undefined).length;r.revealed[stage]=true;}broadcast(r);return {};});
handle('teacher:keys-open',p=>{const r=teacher(p);current(r,p);if(STAGES[r.step]!=='keys')throw Error('Open Key Ideas first.');r.revealed.keys=false;if(r.answersShown)r.answersShown.keys=false;r.groups.forEach(g=>{if(g.submissions.keys)g.drafts.keys=structuredClone(g.submissions.keys);delete g.submissions.keys;delete g.submitTime?.keys;});broadcast(r);return {};});
handle('teacher:peer-open',p=>{const r=teacher(p);current(r,p);if(STAGES[r.step]!=='peer')throw Error('Open Check & Revise first.');r.revealed.peer=false;if(r.answersShown)r.answersShown.peer=false;broadcast(r);return {};});
handle('teacher:previous',p=>{const r=teacher(p);current(r,p);const stage=STAGES[r.step];if(r.step===0)throw Error('This is the first activity.');if(stage==='exit'&&r.finalOrder==='awards-first')r.step=STAGES.indexOf('awards');else if(stage==='awards'&&r.finalOrder==='awards-first')r.step=STAGES.indexOf('summary');else if(stage==='exit'&&r.finalOrder==='exit-first')r.step=STAGES.indexOf('summary');else r.step--;broadcast(r);return {};});
handle('teacher:next',p=>{const r=teacher(p);current(r,p);const stage=STAGES[r.step];if(stage==='summary'&&!r.finalOrder)r.finalOrder='exit-first';let nextStep=r.step+1;if(stage==='summary')nextStep=STAGES.indexOf(r.finalOrder==='awards-first'?'awards':'exit');else if(stage==='awards'&&r.finalOrder==='awards-first')nextStep=STAGES.indexOf('exit');else if(stage==='exit'&&r.finalOrder==='awards-first')nextStep=-1;if(nextStep<0||stage==='awards'&&r.finalOrder!=='awards-first')throw Error('This is the final step.');if(stage==='demo'){r.keysAttempt=(r.keysAttempt||0)+1;r.revealed.keys=false;if(r.answersShown)r.answersShown.keys=false;r.groups.forEach(g=>{if(g.submissions.keys)g.drafts.keys=structuredClone(g.submissions.keys);delete g.submissions.keys;delete g.submitTime?.keys;delete g.closedDrafts?.keys;});}if(stage==='bridgeDemo'){r.bridgeAttempt=(r.bridgeAttempt||0)+1;r.revealed.combined=false;r.revealed.peer=false;if(r.answersShown)r.answersShown.peer=false;r.groups.forEach(g=>{if(g.submissions.combined)g.drafts.combined=structuredClone(g.submissions.combined);delete g.submissions.combined;delete g.submitTime?.combined;delete g.submissions.peer;delete g.closedDrafts?.combined;delete g.closedDrafts?.peer;g.drafts.peer=[];g.feedback=null;g.target=null;});}if(stage==='keys'&&!r.revealed.bridgeDemo)r.demo={key:MODEL.key,who:null,evidence:[],phase:0,revealed:false};if(['keys','combined'].includes(stage))closeDrafts(r,stage);if(stage==='combined'){r.groups.forEach(g=>{if(g.target)return;g.target=g.id%r.groups.length+1;g.drafts.peer=[];});}r.step=nextStep;r.phaseStarted??={};if(['keys','combined','exit'].includes(STAGES[r.step])){if(stage==='demo'||stage==='bridgeDemo'||!r.phaseStarted[STAGES[r.step]])r.phaseStarted[STAGES[r.step]]=Date.now();}broadcast(r);return {};});
handle('lesson:draft',p=>{const {r,s,g}=student();current(r,p);const stage=STAGES[r.step],d=LESSON[stage];if(!d||d.kind==='homework'||r.revealed[stage]||g.lessonAnswers?.[stage]!==undefined)throw Error('This activity is closed.');const a=p.answer; if(d.kind==='response'){if(typeof a!=='string'||a.length>1500)throw Error('Use at most 1500 characters.');}else if(!Array.isArray(a)||a.length!==d.questions.length)throw Error('Complete the current activity.');else if(d.kind==='exit'){if(a.some(v=>!v||(v.key!=null&&(!Number.isInteger(v.key)||v.key<0||v.key>=KEYS.length))||v.who!==null&&!['A','B','C','D'].includes(v.who)||!Array.isArray(v.evidence)||v.evidence.length>20||v.evidence.some(id=>![...SENTENCES,...EVIDENCE_UNITS].some(s=>s.id===id))))throw Error('Choose valid Who and evidence.');}else if(a.some((v,i)=>v!==null&&(!Number.isInteger(v)||v<0||v>=d.questions[i].options.length)))throw Error('Choose a valid option.');g.lessonDrafts??={};if(p.index!==undefined){if(!Number.isInteger(p.index)||p.index<0||p.index>=d.questions.length)throw Error('Choose a current question.');const merged=g.lessonDrafts[stage]||d.questions.map(()=>d.kind==='exit'?{key:null,who:null,evidence:[]}:null);merged[p.index]=structuredClone(a[p.index]);g.lessonDrafts[stage]=merged;}else g.lessonDrafts[stage]=structuredClone(a);broadcast(r);return {personal:privateState(r,s)};});
handle('lesson:submit',p=>{const {r,s,g}=student();current(r,p);const stage=STAGES[r.step],d=LESSON[stage],a=g.lessonDrafts?.[stage];if(!d||d.kind==='homework'||r.revealed[stage]||g.lessonAnswers?.[stage]!==undefined)throw Error('This activity is closed.');if(d.kind==='response'?typeof a!=='string'||a.trim().length<40:d.kind==='exit'?!Array.isArray(a)||a.some(v=>!valid(v)||!Number.isInteger(v.key)||v.key<0||v.key>=KEYS.length):!Array.isArray(a)||a.some(v=>!Number.isInteger(v)))throw Error('Complete all answers before submitting.');g.lessonAnswers??={};g.lessonAnswers[stage]=structuredClone(a);g.lessonOrder??={};g.submitTime??={};g.submitTime[stage]=Date.now();g.lessonOrder[stage]=r.groups.filter(x=>x.lessonAnswers?.[stage]!==undefined).length;broadcast(r);return {personal:privateState(r,s)};});
handle('teacher:reset',p=>{const r=teacher(p);current(r,p);r.round++;r.step=0;r.finalOrder=null;r.awardsCelebrating=false;r.phaseStarted={};r.answersShown={};r.revealed={};r.demo={key:null,who:null,evidence:[],phase:0,revealed:false,markings:[]};r.groups.forEach(g=>{g.award=null;g.lessonAnswers={};g.lessonDrafts={};g.lessonOrder={};g.submitTime={};g.markings=blankMarks();g.drafts={keys:blankKeys(),combined:bridgeDrafts(groupQuestions(g)),peer:[]};g.submissions={};g.closedDrafts={};g.feedback=null;g.target=null;});for(const s of r.students.values()){s.exit=null;s.notes='';s.notesRevision=0;}broadcast(r);return {};});
socket.on('disconnect',()=>{const r=rooms.get(socket.data.code);if(r){r.students.get(socket.data.id)?.sockets.delete(socket.id);r.observers.get(socket.data.id)?.sockets.delete(socket.id);r.lastActive=Date.now();broadcast(r);}});
});const timer=setInterval(()=>{for(const [code,r]of rooms)if(!io.sockets.adapter.rooms.get(code)?.size&&Date.now()-r.lastActive>21600000)rooms.delete(code);},60000);timer.unref();server.on('close',()=>clearInterval(timer));return {app,server,io};}
if(require.main===module){const a=createApp();a.server.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('Young Volunteers · 5 groups + all 6 matching questions'));}module.exports={createApp,MODEL};
